# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/v1/maintenance/maintenance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mesos.v1 import mesos_pb2 as mesos_dot_v1_dot_mesos__pb2
from mesos.v1.allocator import allocator_pb2 as mesos_dot_v1_dot_allocator_dot_allocator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/v1/maintenance/maintenance.proto',
  package='mesos.v1.maintenance',
  syntax='proto2',
  serialized_pb=_b('\n&mesos/v1/maintenance/maintenance.proto\x12\x14mesos.v1.maintenance\x1a\x14mesos/v1/mesos.proto\x1a\"mesos/v1/allocator/allocator.proto\"d\n\x06Window\x12(\n\x0bmachine_ids\x18\x01 \x03(\x0b\x32\x13.mesos.v1.MachineID\x12\x30\n\x0eunavailability\x18\x02 \x02(\x0b\x32\x18.mesos.v1.Unavailability\"9\n\x08Schedule\x12-\n\x07windows\x18\x01 \x03(\x0b\x32\x1c.mesos.v1.maintenance.Window\"\xf9\x01\n\rClusterStatus\x12N\n\x11\x64raining_machines\x18\x01 \x03(\x0b\x32\x33.mesos.v1.maintenance.ClusterStatus.DrainingMachine\x12*\n\rdown_machines\x18\x02 \x03(\x0b\x32\x13.mesos.v1.MachineID\x1al\n\x0f\x44rainingMachine\x12\x1f\n\x02id\x18\x01 \x02(\x0b\x32\x13.mesos.v1.MachineID\x12\x38\n\x08statuses\x18\x02 \x03(\x0b\x32&.mesos.v1.allocator.InverseOfferStatusB)\n\x1forg.apache.mesos.v1.maintenanceB\x06Protos')
  ,
  dependencies=[mesos_dot_v1_dot_mesos__pb2.DESCRIPTOR,mesos_dot_v1_dot_allocator_dot_allocator__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WINDOW = _descriptor.Descriptor(
  name='Window',
  full_name='mesos.v1.maintenance.Window',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_ids', full_name='mesos.v1.maintenance.Window.machine_ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unavailability', full_name='mesos.v1.maintenance.Window.unavailability', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=222,
)


_SCHEDULE = _descriptor.Descriptor(
  name='Schedule',
  full_name='mesos.v1.maintenance.Schedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='windows', full_name='mesos.v1.maintenance.Schedule.windows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=281,
)


_CLUSTERSTATUS_DRAININGMACHINE = _descriptor.Descriptor(
  name='DrainingMachine',
  full_name='mesos.v1.maintenance.ClusterStatus.DrainingMachine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mesos.v1.maintenance.ClusterStatus.DrainingMachine.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statuses', full_name='mesos.v1.maintenance.ClusterStatus.DrainingMachine.statuses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=533,
)

_CLUSTERSTATUS = _descriptor.Descriptor(
  name='ClusterStatus',
  full_name='mesos.v1.maintenance.ClusterStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='draining_machines', full_name='mesos.v1.maintenance.ClusterStatus.draining_machines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='down_machines', full_name='mesos.v1.maintenance.ClusterStatus.down_machines', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLUSTERSTATUS_DRAININGMACHINE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=533,
)

_WINDOW.fields_by_name['machine_ids'].message_type = mesos_dot_v1_dot_mesos__pb2._MACHINEID
_WINDOW.fields_by_name['unavailability'].message_type = mesos_dot_v1_dot_mesos__pb2._UNAVAILABILITY
_SCHEDULE.fields_by_name['windows'].message_type = _WINDOW
_CLUSTERSTATUS_DRAININGMACHINE.fields_by_name['id'].message_type = mesos_dot_v1_dot_mesos__pb2._MACHINEID
_CLUSTERSTATUS_DRAININGMACHINE.fields_by_name['statuses'].message_type = mesos_dot_v1_dot_allocator_dot_allocator__pb2._INVERSEOFFERSTATUS
_CLUSTERSTATUS_DRAININGMACHINE.containing_type = _CLUSTERSTATUS
_CLUSTERSTATUS.fields_by_name['draining_machines'].message_type = _CLUSTERSTATUS_DRAININGMACHINE
_CLUSTERSTATUS.fields_by_name['down_machines'].message_type = mesos_dot_v1_dot_mesos__pb2._MACHINEID
DESCRIPTOR.message_types_by_name['Window'] = _WINDOW
DESCRIPTOR.message_types_by_name['Schedule'] = _SCHEDULE
DESCRIPTOR.message_types_by_name['ClusterStatus'] = _CLUSTERSTATUS

Window = _reflection.GeneratedProtocolMessageType('Window', (_message.Message,), dict(
  DESCRIPTOR = _WINDOW,
  __module__ = 'mesos.v1.maintenance.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:mesos.v1.maintenance.Window)
  ))
_sym_db.RegisterMessage(Window)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULE,
  __module__ = 'mesos.v1.maintenance.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:mesos.v1.maintenance.Schedule)
  ))
_sym_db.RegisterMessage(Schedule)

ClusterStatus = _reflection.GeneratedProtocolMessageType('ClusterStatus', (_message.Message,), dict(

  DrainingMachine = _reflection.GeneratedProtocolMessageType('DrainingMachine', (_message.Message,), dict(
    DESCRIPTOR = _CLUSTERSTATUS_DRAININGMACHINE,
    __module__ = 'mesos.v1.maintenance.maintenance_pb2'
    # @@protoc_insertion_point(class_scope:mesos.v1.maintenance.ClusterStatus.DrainingMachine)
    ))
  ,
  DESCRIPTOR = _CLUSTERSTATUS,
  __module__ = 'mesos.v1.maintenance.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:mesos.v1.maintenance.ClusterStatus)
  ))
_sym_db.RegisterMessage(ClusterStatus)
_sym_db.RegisterMessage(ClusterStatus.DrainingMachine)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.apache.mesos.v1.maintenanceB\006Protos'))
# @@protoc_insertion_point(module_scope)
