# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/docker/spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/docker/spec.proto',
  package='docker.spec',
  syntax='proto2',
  serialized_pb=_b('\n\x17mesos/docker/spec.proto\x12\x0b\x64ocker.spec\"S\n\x0eImageReference\x12\x10\n\x08registry\x18\x01 \x01(\t\x12\x12\n\nrepository\x18\x02 \x02(\t\x12\x0b\n\x03tag\x18\x03 \x01(\t\x12\x0e\n\x06\x64igest\x18\x04 \x01(\t\"-\n\x06\x43onfig\x1a#\n\x04\x41uth\x12\x0c\n\x04\x61uth\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMAGEREFERENCE = _descriptor.Descriptor(
  name='ImageReference',
  full_name='docker.spec.ImageReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registry', full_name='docker.spec.ImageReference.registry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repository', full_name='docker.spec.ImageReference.repository', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='docker.spec.ImageReference.tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='digest', full_name='docker.spec.ImageReference.digest', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=123,
)


_CONFIG_AUTH = _descriptor.Descriptor(
  name='Auth',
  full_name='docker.spec.Config.Auth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='docker.spec.Config.Auth.auth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='docker.spec.Config.Auth.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=170,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='docker.spec.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_AUTH, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=170,
)

_CONFIG_AUTH.containing_type = _CONFIG
DESCRIPTOR.message_types_by_name['ImageReference'] = _IMAGEREFERENCE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG

ImageReference = _reflection.GeneratedProtocolMessageType('ImageReference', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREFERENCE,
  __module__ = 'mesos.docker.spec_pb2'
  # @@protoc_insertion_point(class_scope:docker.spec.ImageReference)
  ))
_sym_db.RegisterMessage(ImageReference)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(

  Auth = _reflection.GeneratedProtocolMessageType('Auth', (_message.Message,), dict(
    DESCRIPTOR = _CONFIG_AUTH,
    __module__ = 'mesos.docker.spec_pb2'
    # @@protoc_insertion_point(class_scope:docker.spec.Config.Auth)
    ))
  ,
  DESCRIPTOR = _CONFIG,
  __module__ = 'mesos.docker.spec_pb2'
  # @@protoc_insertion_point(class_scope:docker.spec.Config)
  ))
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.Auth)


# @@protoc_insertion_point(module_scope)
