# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/docker/v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/docker/v1.proto',
  package='docker.spec.v1',
  syntax='proto2',
  serialized_pb=_b('\n\x15mesos/docker/v1.proto\x12\x0e\x64ocker.spec.v1\"#\n\x05Label\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xd1\x03\n\rImageManifest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\x0f\n\x07\x63reated\x18\x04 \x01(\t\x12\x11\n\tcontainer\x18\x05 \x01(\t\x12>\n\x10\x63ontainer_config\x18\x06 \x01(\x0b\x32$.docker.spec.v1.ImageManifest.Config\x12\x16\n\x0e\x64ocker_version\x18\x07 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x08 \x01(\t\x12\x34\n\x06\x63onfig\x18\t \x01(\x0b\x32$.docker.spec.v1.ImageManifest.Config\x12\x14\n\x0c\x61rchitecture\x18\n \x01(\t\x12\n\n\x02os\x18\x0b \x01(\t\x12\x0c\n\x04Size\x18\x0c \x01(\r\x1a\xa0\x01\n\x06\x43onfig\x12\x10\n\x08Hostname\x18\x01 \x01(\t\x12\x12\n\nEntrypoint\x18\x02 \x03(\t\x12\x0b\n\x03\x45nv\x18\x03 \x03(\t\x12\x0c\n\x04User\x18\x04 \x01(\t\x12\x0b\n\x03\x43md\x18\x05 \x03(\t\x12\x12\n\nWorkingDir\x18\x06 \x01(\t\x12\r\n\x05Image\x18\x08 \x01(\t\x12%\n\x06labels\x18\t \x03(\x0b\x32\x15.docker.spec.v1.Label')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='docker.spec.v1.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='docker.spec.v1.Label.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='docker.spec.v1.Label.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=76,
)


_IMAGEMANIFEST_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='docker.spec.v1.ImageManifest.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hostname', full_name='docker.spec.v1.ImageManifest.Config.Hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Entrypoint', full_name='docker.spec.v1.ImageManifest.Config.Entrypoint', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Env', full_name='docker.spec.v1.ImageManifest.Config.Env', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='User', full_name='docker.spec.v1.ImageManifest.Config.User', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='docker.spec.v1.ImageManifest.Config.Cmd', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WorkingDir', full_name='docker.spec.v1.ImageManifest.Config.WorkingDir', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Image', full_name='docker.spec.v1.ImageManifest.Config.Image', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='docker.spec.v1.ImageManifest.Config.labels', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=544,
)

_IMAGEMANIFEST = _descriptor.Descriptor(
  name='ImageManifest',
  full_name='docker.spec.v1.ImageManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='docker.spec.v1.ImageManifest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='docker.spec.v1.ImageManifest.parent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='docker.spec.v1.ImageManifest.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='docker.spec.v1.ImageManifest.created', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container', full_name='docker.spec.v1.ImageManifest.container', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_config', full_name='docker.spec.v1.ImageManifest.container_config', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docker_version', full_name='docker.spec.v1.ImageManifest.docker_version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='docker.spec.v1.ImageManifest.author', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config', full_name='docker.spec.v1.ImageManifest.config', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='architecture', full_name='docker.spec.v1.ImageManifest.architecture', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='os', full_name='docker.spec.v1.ImageManifest.os', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Size', full_name='docker.spec.v1.ImageManifest.Size', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMANIFEST_CONFIG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=544,
)

_IMAGEMANIFEST_CONFIG.fields_by_name['labels'].message_type = _LABEL
_IMAGEMANIFEST_CONFIG.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST.fields_by_name['container_config'].message_type = _IMAGEMANIFEST_CONFIG
_IMAGEMANIFEST.fields_by_name['config'].message_type = _IMAGEMANIFEST_CONFIG
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['ImageManifest'] = _IMAGEMANIFEST

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'mesos.docker.v1_pb2'
  # @@protoc_insertion_point(class_scope:docker.spec.v1.Label)
  ))
_sym_db.RegisterMessage(Label)

ImageManifest = _reflection.GeneratedProtocolMessageType('ImageManifest', (_message.Message,), dict(

  Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_CONFIG,
    __module__ = 'mesos.docker.v1_pb2'
    # @@protoc_insertion_point(class_scope:docker.spec.v1.ImageManifest.Config)
    ))
  ,
  DESCRIPTOR = _IMAGEMANIFEST,
  __module__ = 'mesos.docker.v1_pb2'
  # @@protoc_insertion_point(class_scope:docker.spec.v1.ImageManifest)
  ))
_sym_db.RegisterMessage(ImageManifest)
_sym_db.RegisterMessage(ImageManifest.Config)


# @@protoc_insertion_point(module_scope)
