# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/docker/v2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mesos.docker import v1_pb2 as mesos_dot_docker_dot_v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/docker/v2.proto',
  package='docker.spec.v2',
  syntax='proto2',
  serialized_pb=_b('\n\x15mesos/docker/v2.proto\x12\x0e\x64ocker.spec.v2\x1a\x15mesos/docker/v1.proto\"\x81\x05\n\rImageManifest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03tag\x18\x02 \x02(\t\x12\x14\n\x0c\x61rchitecture\x18\x03 \x02(\t\x12\x37\n\x08\x66sLayers\x18\x04 \x03(\x0b\x32%.docker.spec.v2.ImageManifest.FsLayer\x12\x36\n\x07history\x18\x05 \x03(\x0b\x32%.docker.spec.v2.ImageManifest.History\x12\x15\n\rschemaVersion\x18\x06 \x02(\r\x12;\n\nsignatures\x18\x07 \x03(\x0b\x32\'.docker.spec.v2.ImageManifest.Signature\x1a\x1a\n\x07\x46sLayer\x12\x0f\n\x07\x62lobSum\x18\x01 \x02(\t\x1aM\n\x07History\x12\x17\n\x0fv1Compatibility\x18\x01 \x02(\t\x12)\n\x02v1\x18\x02 \x01(\x0b\x32\x1d.docker.spec.v1.ImageManifest\x1a\x8e\x02\n\tSignature\x12>\n\x06header\x18\x01 \x02(\x0b\x32..docker.spec.v2.ImageManifest.Signature.Header\x12\x11\n\tsignature\x18\x02 \x02(\t\x12\x11\n\tprotected\x18\x03 \x02(\t\x1a\x9a\x01\n\x06Header\x12?\n\x03jwk\x18\x01 \x01(\x0b\x32\x32.docker.spec.v2.ImageManifest.Signature.Header.Jwk\x12\x0b\n\x03\x61lg\x18\x02 \x02(\t\x1a\x42\n\x03Jwk\x12\x0b\n\x03\x63rv\x18\x01 \x01(\t\x12\x0b\n\x03kid\x18\x02 \x01(\t\x12\x0b\n\x03kty\x18\x03 \x02(\t\x12\t\n\x01x\x18\x04 \x01(\t\x12\t\n\x01y\x18\x05 \x01(\t')
  ,
  dependencies=[mesos_dot_docker_dot_v1__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMAGEMANIFEST_FSLAYER = _descriptor.Descriptor(
  name='FsLayer',
  full_name='docker.spec.v2.ImageManifest.FsLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blobSum', full_name='docker.spec.v2.ImageManifest.FsLayer.blobSum', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=354,
)

_IMAGEMANIFEST_HISTORY = _descriptor.Descriptor(
  name='History',
  full_name='docker.spec.v2.ImageManifest.History',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v1Compatibility', full_name='docker.spec.v2.ImageManifest.History.v1Compatibility', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v1', full_name='docker.spec.v2.ImageManifest.History.v1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=433,
)

_IMAGEMANIFEST_SIGNATURE_HEADER_JWK = _descriptor.Descriptor(
  name='Jwk',
  full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crv', full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk.crv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kid', full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk.kid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kty', full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk.kty', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk.x', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='docker.spec.v2.ImageManifest.Signature.Header.Jwk.y', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=706,
)

_IMAGEMANIFEST_SIGNATURE_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='docker.spec.v2.ImageManifest.Signature.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jwk', full_name='docker.spec.v2.ImageManifest.Signature.Header.jwk', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alg', full_name='docker.spec.v2.ImageManifest.Signature.Header.alg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMANIFEST_SIGNATURE_HEADER_JWK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=706,
)

_IMAGEMANIFEST_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='docker.spec.v2.ImageManifest.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='docker.spec.v2.ImageManifest.Signature.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='docker.spec.v2.ImageManifest.Signature.signature', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protected', full_name='docker.spec.v2.ImageManifest.Signature.protected', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMANIFEST_SIGNATURE_HEADER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=706,
)

_IMAGEMANIFEST = _descriptor.Descriptor(
  name='ImageManifest',
  full_name='docker.spec.v2.ImageManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='docker.spec.v2.ImageManifest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='docker.spec.v2.ImageManifest.tag', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='architecture', full_name='docker.spec.v2.ImageManifest.architecture', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fsLayers', full_name='docker.spec.v2.ImageManifest.fsLayers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='history', full_name='docker.spec.v2.ImageManifest.history', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='schemaVersion', full_name='docker.spec.v2.ImageManifest.schemaVersion', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='docker.spec.v2.ImageManifest.signatures', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMANIFEST_FSLAYER, _IMAGEMANIFEST_HISTORY, _IMAGEMANIFEST_SIGNATURE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=706,
)

_IMAGEMANIFEST_FSLAYER.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_HISTORY.fields_by_name['v1'].message_type = mesos_dot_docker_dot_v1__pb2._IMAGEMANIFEST
_IMAGEMANIFEST_HISTORY.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_SIGNATURE_HEADER_JWK.containing_type = _IMAGEMANIFEST_SIGNATURE_HEADER
_IMAGEMANIFEST_SIGNATURE_HEADER.fields_by_name['jwk'].message_type = _IMAGEMANIFEST_SIGNATURE_HEADER_JWK
_IMAGEMANIFEST_SIGNATURE_HEADER.containing_type = _IMAGEMANIFEST_SIGNATURE
_IMAGEMANIFEST_SIGNATURE.fields_by_name['header'].message_type = _IMAGEMANIFEST_SIGNATURE_HEADER
_IMAGEMANIFEST_SIGNATURE.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST.fields_by_name['fsLayers'].message_type = _IMAGEMANIFEST_FSLAYER
_IMAGEMANIFEST.fields_by_name['history'].message_type = _IMAGEMANIFEST_HISTORY
_IMAGEMANIFEST.fields_by_name['signatures'].message_type = _IMAGEMANIFEST_SIGNATURE
DESCRIPTOR.message_types_by_name['ImageManifest'] = _IMAGEMANIFEST

ImageManifest = _reflection.GeneratedProtocolMessageType('ImageManifest', (_message.Message,), dict(

  FsLayer = _reflection.GeneratedProtocolMessageType('FsLayer', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_FSLAYER,
    __module__ = 'mesos.docker.v2_pb2'
    # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest.FsLayer)
    ))
  ,

  History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_HISTORY,
    __module__ = 'mesos.docker.v2_pb2'
    # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest.History)
    ))
  ,

  Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(

    Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(

      Jwk = _reflection.GeneratedProtocolMessageType('Jwk', (_message.Message,), dict(
        DESCRIPTOR = _IMAGEMANIFEST_SIGNATURE_HEADER_JWK,
        __module__ = 'mesos.docker.v2_pb2'
        # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest.Signature.Header.Jwk)
        ))
      ,
      DESCRIPTOR = _IMAGEMANIFEST_SIGNATURE_HEADER,
      __module__ = 'mesos.docker.v2_pb2'
      # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest.Signature.Header)
      ))
    ,
    DESCRIPTOR = _IMAGEMANIFEST_SIGNATURE,
    __module__ = 'mesos.docker.v2_pb2'
    # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest.Signature)
    ))
  ,
  DESCRIPTOR = _IMAGEMANIFEST,
  __module__ = 'mesos.docker.v2_pb2'
  # @@protoc_insertion_point(class_scope:docker.spec.v2.ImageManifest)
  ))
_sym_db.RegisterMessage(ImageManifest)
_sym_db.RegisterMessage(ImageManifest.FsLayer)
_sym_db.RegisterMessage(ImageManifest.History)
_sym_db.RegisterMessage(ImageManifest.Signature)
_sym_db.RegisterMessage(ImageManifest.Signature.Header)
_sym_db.RegisterMessage(ImageManifest.Signature.Header.Jwk)


# @@protoc_insertion_point(module_scope)
