# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/appc/spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/appc/spec.proto',
  package='appc.spec',
  syntax='proto2',
  serialized_pb=_b('\n\x15mesos/appc/spec.proto\x12\tappc.spec\"\xe7\x04\n\rImageManifest\x12\x0e\n\x06\x61\x63Kind\x18\x01 \x02(\t\x12\x11\n\tacVersion\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12.\n\x06labels\x18\x04 \x03(\x0b\x32\x1e.appc.spec.ImageManifest.Label\x12)\n\x03\x61pp\x18\x07 \x01(\x0b\x32\x1c.appc.spec.ImageManifest.App\x12\x38\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32#.appc.spec.ImageManifest.Annotation\x12\x39\n\x0c\x64\x65pendencies\x18\x06 \x03(\x0b\x32#.appc.spec.ImageManifest.Dependency\x1a$\n\x05Label\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a*\n\x0b\x45nvironment\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1ah\n\x03\x41pp\x12\x0c\n\x04\x65xec\x18\x01 \x03(\t\x12\x18\n\x10workingDirectory\x18\x02 \x01(\t\x12\x39\n\x0b\x65nvironment\x18\x03 \x03(\x0b\x32$.appc.spec.ImageManifest.Environment\x1a)\n\nAnnotation\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1an\n\nDependency\x12\x11\n\timageName\x18\x01 \x02(\t\x12\x0f\n\x07imageID\x18\x02 \x01(\t\x12.\n\x06labels\x18\x03 \x03(\x0b\x32\x1e.appc.spec.ImageManifest.Label\x12\x0c\n\x04size\x18\x04 \x01(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMAGEMANIFEST_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='appc.spec.ImageManifest.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='appc.spec.ImageManifest.Label.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='appc.spec.ImageManifest.Label.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=347,
)

_IMAGEMANIFEST_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='appc.spec.ImageManifest.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='appc.spec.ImageManifest.Environment.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='appc.spec.ImageManifest.Environment.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=391,
)

_IMAGEMANIFEST_APP = _descriptor.Descriptor(
  name='App',
  full_name='appc.spec.ImageManifest.App',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exec', full_name='appc.spec.ImageManifest.App.exec', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workingDirectory', full_name='appc.spec.ImageManifest.App.workingDirectory', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='environment', full_name='appc.spec.ImageManifest.App.environment', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=497,
)

_IMAGEMANIFEST_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='appc.spec.ImageManifest.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='appc.spec.ImageManifest.Annotation.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='appc.spec.ImageManifest.Annotation.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=540,
)

_IMAGEMANIFEST_DEPENDENCY = _descriptor.Descriptor(
  name='Dependency',
  full_name='appc.spec.ImageManifest.Dependency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageName', full_name='appc.spec.ImageManifest.Dependency.imageName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageID', full_name='appc.spec.ImageManifest.Dependency.imageID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='appc.spec.ImageManifest.Dependency.labels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='appc.spec.ImageManifest.Dependency.size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=652,
)

_IMAGEMANIFEST = _descriptor.Descriptor(
  name='ImageManifest',
  full_name='appc.spec.ImageManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acKind', full_name='appc.spec.ImageManifest.acKind', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acVersion', full_name='appc.spec.ImageManifest.acVersion', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='appc.spec.ImageManifest.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='appc.spec.ImageManifest.labels', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='appc.spec.ImageManifest.app', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='appc.spec.ImageManifest.annotations', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='appc.spec.ImageManifest.dependencies', index=6,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMANIFEST_LABEL, _IMAGEMANIFEST_ENVIRONMENT, _IMAGEMANIFEST_APP, _IMAGEMANIFEST_ANNOTATION, _IMAGEMANIFEST_DEPENDENCY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=652,
)

_IMAGEMANIFEST_LABEL.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_ENVIRONMENT.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_APP.fields_by_name['environment'].message_type = _IMAGEMANIFEST_ENVIRONMENT
_IMAGEMANIFEST_APP.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_ANNOTATION.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST_DEPENDENCY.fields_by_name['labels'].message_type = _IMAGEMANIFEST_LABEL
_IMAGEMANIFEST_DEPENDENCY.containing_type = _IMAGEMANIFEST
_IMAGEMANIFEST.fields_by_name['labels'].message_type = _IMAGEMANIFEST_LABEL
_IMAGEMANIFEST.fields_by_name['app'].message_type = _IMAGEMANIFEST_APP
_IMAGEMANIFEST.fields_by_name['annotations'].message_type = _IMAGEMANIFEST_ANNOTATION
_IMAGEMANIFEST.fields_by_name['dependencies'].message_type = _IMAGEMANIFEST_DEPENDENCY
DESCRIPTOR.message_types_by_name['ImageManifest'] = _IMAGEMANIFEST

ImageManifest = _reflection.GeneratedProtocolMessageType('ImageManifest', (_message.Message,), dict(

  Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_LABEL,
    __module__ = 'mesos.appc.spec_pb2'
    # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest.Label)
    ))
  ,

  Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_ENVIRONMENT,
    __module__ = 'mesos.appc.spec_pb2'
    # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest.Environment)
    ))
  ,

  App = _reflection.GeneratedProtocolMessageType('App', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_APP,
    __module__ = 'mesos.appc.spec_pb2'
    # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest.App)
    ))
  ,

  Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_ANNOTATION,
    __module__ = 'mesos.appc.spec_pb2'
    # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest.Annotation)
    ))
  ,

  Dependency = _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), dict(
    DESCRIPTOR = _IMAGEMANIFEST_DEPENDENCY,
    __module__ = 'mesos.appc.spec_pb2'
    # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest.Dependency)
    ))
  ,
  DESCRIPTOR = _IMAGEMANIFEST,
  __module__ = 'mesos.appc.spec_pb2'
  # @@protoc_insertion_point(class_scope:appc.spec.ImageManifest)
  ))
_sym_db.RegisterMessage(ImageManifest)
_sym_db.RegisterMessage(ImageManifest.Label)
_sym_db.RegisterMessage(ImageManifest.Environment)
_sym_db.RegisterMessage(ImageManifest.App)
_sym_db.RegisterMessage(ImageManifest.Annotation)
_sym_db.RegisterMessage(ImageManifest.Dependency)


# @@protoc_insertion_point(module_scope)
