# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/fetcher/fetcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mesos import mesos_pb2 as mesos_dot_mesos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/fetcher/fetcher.proto',
  package='mesos.fetcher',
  syntax='proto2',
  serialized_pb=_b('\n\x1bmesos/fetcher/fetcher.proto\x12\rmesos.fetcher\x1a\x11mesos/mesos.proto\"\xe3\x02\n\x0b\x46\x65tcherInfo\x12\x19\n\x11sandbox_directory\x18\x01 \x02(\t\x12\x17\n\x0f\x63\x61\x63he_directory\x18\x02 \x01(\t\x12.\n\x05items\x18\x03 \x03(\x0b\x32\x1f.mesos.fetcher.FetcherInfo.Item\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\x17\n\x0f\x66rameworks_home\x18\x05 \x01(\t\x1a\xc8\x01\n\x04Item\x12#\n\x03uri\x18\x01 \x02(\x0b\x32\x16.mesos.CommandInfo.URI\x12\x36\n\x06\x61\x63tion\x18\x02 \x02(\x0e\x32&.mesos.fetcher.FetcherInfo.Item.Action\x12\x16\n\x0e\x63\x61\x63he_filename\x18\x03 \x01(\t\"K\n\x06\x41\x63tion\x12\x10\n\x0c\x42YPASS_CACHE\x10\x00\x12\x16\n\x12\x44OWNLOAD_AND_CACHE\x10\x01\x12\x17\n\x13RETRIEVE_FROM_CACHE\x10\x02\x42\"\n\x18org.apache.mesos.fetcherB\x06Protos')
  ,
  dependencies=[mesos_dot_mesos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FETCHERINFO_ITEM_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='mesos.fetcher.FetcherInfo.Item.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BYPASS_CACHE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNLOAD_AND_CACHE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETRIEVE_FROM_CACHE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=346,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_FETCHERINFO_ITEM_ACTION)


_FETCHERINFO_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='mesos.fetcher.FetcherInfo.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='mesos.fetcher.FetcherInfo.Item.uri', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='mesos.fetcher.FetcherInfo.Item.action', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_filename', full_name='mesos.fetcher.FetcherInfo.Item.cache_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FETCHERINFO_ITEM_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=421,
)

_FETCHERINFO = _descriptor.Descriptor(
  name='FetcherInfo',
  full_name='mesos.fetcher.FetcherInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sandbox_directory', full_name='mesos.fetcher.FetcherInfo.sandbox_directory', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_directory', full_name='mesos.fetcher.FetcherInfo.cache_directory', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='mesos.fetcher.FetcherInfo.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='mesos.fetcher.FetcherInfo.user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frameworks_home', full_name='mesos.fetcher.FetcherInfo.frameworks_home', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FETCHERINFO_ITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=421,
)

_FETCHERINFO_ITEM.fields_by_name['uri'].message_type = mesos_dot_mesos__pb2._COMMANDINFO_URI
_FETCHERINFO_ITEM.fields_by_name['action'].enum_type = _FETCHERINFO_ITEM_ACTION
_FETCHERINFO_ITEM.containing_type = _FETCHERINFO
_FETCHERINFO_ITEM_ACTION.containing_type = _FETCHERINFO_ITEM
_FETCHERINFO.fields_by_name['items'].message_type = _FETCHERINFO_ITEM
DESCRIPTOR.message_types_by_name['FetcherInfo'] = _FETCHERINFO

FetcherInfo = _reflection.GeneratedProtocolMessageType('FetcherInfo', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _FETCHERINFO_ITEM,
    __module__ = 'mesos.fetcher.fetcher_pb2'
    # @@protoc_insertion_point(class_scope:mesos.fetcher.FetcherInfo.Item)
    ))
  ,
  DESCRIPTOR = _FETCHERINFO,
  __module__ = 'mesos.fetcher.fetcher_pb2'
  # @@protoc_insertion_point(class_scope:mesos.fetcher.FetcherInfo)
  ))
_sym_db.RegisterMessage(FetcherInfo)
_sym_db.RegisterMessage(FetcherInfo.Item)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030org.apache.mesos.fetcherB\006Protos'))
# @@protoc_insertion_point(module_scope)
