# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesos/allocator/allocator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mesos import mesos_pb2 as mesos_dot_mesos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mesos/allocator/allocator.proto',
  package='mesos.allocator',
  syntax='proto2',
  serialized_pb=_b('\n\x1fmesos/allocator/allocator.proto\x12\x0fmesos.allocator\x1a\x11mesos/mesos.proto\"\xce\x01\n\x12InverseOfferStatus\x12:\n\x06status\x18\x01 \x02(\x0e\x32*.mesos.allocator.InverseOfferStatus.Status\x12(\n\x0c\x66ramework_id\x18\x02 \x02(\x0b\x32\x12.mesos.FrameworkID\x12\"\n\ttimestamp\x18\x03 \x02(\x0b\x32\x0f.mesos.TimeInfo\".\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x01\x12\n\n\x06\x41\x43\x43\x45PT\x10\x02\x12\x0b\n\x07\x44\x45\x43LINE\x10\x03')
  ,
  dependencies=[mesos_dot_mesos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INVERSEOFFERSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='mesos.allocator.InverseOfferStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECLINE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=232,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_INVERSEOFFERSTATUS_STATUS)


_INVERSEOFFERSTATUS = _descriptor.Descriptor(
  name='InverseOfferStatus',
  full_name='mesos.allocator.InverseOfferStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mesos.allocator.InverseOfferStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='framework_id', full_name='mesos.allocator.InverseOfferStatus.framework_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mesos.allocator.InverseOfferStatus.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INVERSEOFFERSTATUS_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=278,
)

_INVERSEOFFERSTATUS.fields_by_name['status'].enum_type = _INVERSEOFFERSTATUS_STATUS
_INVERSEOFFERSTATUS.fields_by_name['framework_id'].message_type = mesos_dot_mesos__pb2._FRAMEWORKID
_INVERSEOFFERSTATUS.fields_by_name['timestamp'].message_type = mesos_dot_mesos__pb2._TIMEINFO
_INVERSEOFFERSTATUS_STATUS.containing_type = _INVERSEOFFERSTATUS
DESCRIPTOR.message_types_by_name['InverseOfferStatus'] = _INVERSEOFFERSTATUS

InverseOfferStatus = _reflection.GeneratedProtocolMessageType('InverseOfferStatus', (_message.Message,), dict(
  DESCRIPTOR = _INVERSEOFFERSTATUS,
  __module__ = 'mesos.allocator.allocator_pb2'
  # @@protoc_insertion_point(class_scope:mesos.allocator.InverseOfferStatus)
  ))
_sym_db.RegisterMessage(InverseOfferStatus)


# @@protoc_insertion_point(module_scope)
